In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5,6]

In [3]:
array1=np.array(list1)

In [4]:
array1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(array1)

numpy.ndarray

In [6]:
dir(array1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [8]:
array1.sum()

21

In [9]:
array2=np.array([1,2,3,4,5,'p'])

In [10]:
array2

array(['1', '2', '3', '4', '5', 'p'], dtype='<U11')

In [11]:
array1.shape

(6,)

In [12]:
array1.size

6

In [13]:
array1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array1

array([1, 2, 3, 4, 5, 6])

In [15]:
array1.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])