In [2]:
import numpy as np

In [6]:
list1=[1,2,3]
list1

[1, 2, 3]

In [5]:
a=np.array(list1)
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [12]:
tuple1=(1,2,32)
tuple1

(1, 2, 32)

In [15]:
b=np.array(tuple1)
b

array([ 1,  2, 32])

In [16]:
tup2=(1,2,3,3,2,4,5,)
tup2

(1, 2, 3, 3, 2, 4, 5)

In [17]:
c=np.array(tup2)
c

array([1, 2, 3, 3, 2, 4, 5])

In [18]:
d=np.array([1,2,54,32])
d

array([ 1,  2, 54, 32])

In [33]:
d.sum()

89

In [34]:
max(d)

54

In [23]:
matrix1=[[1,2,3],[3,4,5],[5,6,7]]
matrix1

[[1, 2, 3], [3, 4, 5], [5, 6, 7]]

In [24]:
e=np.array(matrix1)
e

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [25]:
f=np.array([[1,2,1],[2,3,2],[3,4,3]])
f

array([[1, 2, 1],
       [2, 3, 2],
       [3, 4, 3]])

In [32]:
f.sum()

21

In [27]:
set1={1,2,3,4,5,6}
set1

{1, 2, 3, 4, 5, 6}

In [28]:
g=np.array(set1)
g

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [30]:
g.sum()

{1, 2, 3, 4, 5, 6}

In [31]:
g.dtype=int64

NameError: name 'int64' is not defined

In [5]:
a=np.arange(1,101)

In [6]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
a.shape

(100,)

In [8]:
a.reshape(25,4)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [9]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
a.shape=(25,4)

In [11]:
a.shape

(25, 4)

In [12]:
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [13]:
a.shape=(5,5,4)

In [14]:
a.shape

(5, 5, 4)

In [15]:
a

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [18]:
b=np.linspace(1,5,11)

In [19]:
b

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [23]:
c=np.random.rand(5)

In [21]:
c

array([0.68982846, 0.58623624, 0.23147866, 0.98173224, 0.51938436])

In [24]:
c

array([0.77510943, 0.33030736, 0.48739928, 0.38865664, 0.88191068])

In [29]:
np.random.randn(7)

array([-0.91463622,  1.03260608, -0.25282171,  1.21151683,  0.4782912 ,
       -0.81607205, -0.92455894])

In [30]:
np.random.randn(7,3)

array([[-0.30903891,  0.16082174, -0.26600519],
       [-0.84774823, -0.63453037, -0.1058889 ],
       [ 1.47685755, -1.02135363, -0.69569087],
       [ 0.07648422, -0.48383947,  0.89914155],
       [-0.15140282,  1.01421662,  0.16913416],
       [-1.20843389, -1.77570464, -1.29048282],
       [-1.49573051, -0.19712904, -0.11055004]])

In [31]:
np.random.randint(1,100,7)

array([41, 28, 53, 87, 97, 77, 29])

In [32]:
np.random.randint(1,10,7)

array([7, 8, 5, 6, 2, 4, 4])

In [35]:
np.random.randint(1,10,17)

array([4, 4, 1, 9, 9, 5, 5, 7, 7, 8, 4, 7, 9, 7, 8, 4, 2])

In [40]:
np.random.seed(100)
d=np.random.randint(1,100,10)

In [41]:
d

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [42]:
d.shape

(10,)

In [185]:
d.shape=(5,2)
d

array([[ 9, 25],
       [68, 88],
       [80, 49],
       [11, 95],
       [53, 99]])

In [46]:
d[2,1]

49

In [47]:
d[3,0]

11

In [51]:
d[2,]

array([80, 49])

In [58]:
d[4]

array([53, 99])

In [59]:
d[0]

array([ 9, 25])

In [95]:
d[:,1:2]

array([[25],
       [88],
       [49],
       [95],
       [99]])

In [94]:
d[:,:1]

array([[ 9],
       [68],
       [80],
       [11],
       [53]])

In [97]:
d[:3,0]

array([ 9, 68, 80])

In [98]:
f=np.arange(1,101)

In [99]:
f

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [100]:
f.shape=(5,5,4)

In [101]:
f

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [104]:
f[0,1,1]

6

In [105]:
f[1,2,1]

30

In [107]:
f[3,4,2]

79

In [117]:
f[1,3:]

array([[33, 34, 35, 36],
       [37, 38, 39, 40]])

In [118]:
f[3,3,:]

array([73, 74, 75, 76])

In [119]:
f[4,4,:]

array([ 97,  98,  99, 100])

In [116]:
f[4,:,:]

array([[ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [121]:
f[4,:,1:3]

array([[82, 83],
       [86, 87],
       [90, 91],
       [94, 95],
       [98, 99]])

In [123]:
f[4,:,1:2]

array([[82],
       [86],
       [90],
       [94],
       [98]])

In [133]:
f[0:3:2,3:,:]

array([[[13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[53, 54, 55, 56],
        [57, 58, 59, 60]]])

In [136]:
f[0::4,3:,:]

array([[[ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [140]:
f[1:4:2,3:,:]

array([[[33, 34, 35, 36],
        [37, 38, 39, 40]],

       [[73, 74, 75, 76],
        [77, 78, 79, 80]]])

In [149]:
f[1::3,3:,:]

array([[[ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [148]:
f[2::2,3:,:]

array([[[ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [150]:
g=np.ones(5)

In [151]:
g

array([1., 1., 1., 1., 1.])

In [152]:
h=np.zeros(10)

In [153]:
h

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
i=np.eye(5)

In [155]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [163]:
dir(i)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [164]:
i+5

array([[6., 5., 5., 5., 5.],
       [5., 6., 5., 5., 5.],
       [5., 5., 6., 5., 5.],
       [5., 5., 5., 6., 5.],
       [5., 5., 5., 5., 6.]])

In [165]:
g+10

array([11., 11., 11., 11., 11.])

In [166]:
i*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [167]:
h-3

array([-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.])

In [172]:
r=np.arange(1,11)

In [173]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [190]:
dir(r)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [174]:
max(r)

10

In [175]:
min(r)

1

In [177]:
sum(r)

55

In [193]:
r.sort()
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
np.trace(i)

5.0

In [184]:
np.transpose(i*5)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [187]:
np.transpose(d)

array([[ 9, 68, 80, 11, 53],
       [25, 88, 49, 95, 99]])

In [188]:
np.trace(i*5)

25.0

In [189]:
np.mean(r)

5.5

In [210]:
z=d.T
z

array([[ 9, 68, 80, 11, 53],
       [25, 88, 49, 95, 99]])

In [211]:
d

array([[ 9, 25],
       [68, 88],
       [80, 49],
       [11, 95],
       [53, 99]])

In [217]:
np.prod(z)

558971392

In [213]:
type(d)

numpy.ndarray

In [214]:
type(z)

numpy.ndarray

In [215]:
np.matmul(d,z)

array([[  706,  2812,  1945,  2474,  2952],
       [ 2812, 12368,  9752,  9108, 12316],
       [ 1945,  9752,  8801,  5535,  9091],
       [ 2474,  9108,  5535,  9146,  9988],
       [ 2952, 12316,  9091,  9988, 12610]])

In [216]:
np.dot(d,z)

array([[  706,  2812,  1945,  2474,  2952],
       [ 2812, 12368,  9752,  9108, 12316],
       [ 1945,  9752,  8801,  5535,  9091],
       [ 2474,  9108,  5535,  9146,  9988],
       [ 2952, 12316,  9091,  9988, 12610]])