In [1]:
import numpy as np

In [7]:
a=np.random.randint(1,1000,100)

In [8]:
a

array([115, 525, 825, 917,  76,  51, 203, 558, 925, 200, 695, 297, 348,
       778, 237, 407,  23, 748, 197, 366, 411, 783,  33, 727, 154, 252,
       244, 729, 609, 496, 580, 688, 565, 732, 889, 426, 174, 358, 802,
       523, 591, 100,  83, 153, 120, 790, 265, 964, 647, 930, 523, 107,
       110, 659, 636, 237, 589, 533, 565, 986, 752, 391,  87, 597,  66,
       880, 429, 118, 609, 845,  80, 673, 732,  53, 761,  67, 339, 902,
       748, 820, 700,   3, 356, 609, 833, 839, 904, 191, 151, 982, 586,
       488,  25, 871, 429, 484,  98, 761, 885, 157])

In [9]:
a.shape=(4,5,5)

In [10]:
a

array([[[115, 525, 825, 917,  76],
        [ 51, 203, 558, 925, 200],
        [695, 297, 348, 778, 237],
        [407,  23, 748, 197, 366],
        [411, 783,  33, 727, 154]],

       [[252, 244, 729, 609, 496],
        [580, 688, 565, 732, 889],
        [426, 174, 358, 802, 523],
        [591, 100,  83, 153, 120],
        [790, 265, 964, 647, 930]],

       [[523, 107, 110, 659, 636],
        [237, 589, 533, 565, 986],
        [752, 391,  87, 597,  66],
        [880, 429, 118, 609, 845],
        [ 80, 673, 732,  53, 761]],

       [[ 67, 339, 902, 748, 820],
        [700,   3, 356, 609, 833],
        [839, 904, 191, 151, 982],
        [586, 488,  25, 871, 429],
        [484,  98, 761, 885, 157]]])

In [11]:
a[1,2,1]

174

In [12]:
a[0,0,0]

115

In [13]:
a[2,2,:]

array([752, 391,  87, 597,  66])

In [14]:
a[2,2:,:]

array([[752, 391,  87, 597,  66],
       [880, 429, 118, 609, 845],
       [ 80, 673, 732,  53, 761]])

In [15]:
a[1,0:,2:4]

array([[729, 609],
       [565, 732],
       [358, 802],
       [ 83, 153],
       [964, 647]])

In [16]:
a[2,0:,1:4:2]

array([[107, 659],
       [589, 565],
       [391, 597],
       [429, 609],
       [673,  53]])

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
np.random.rand()

0.7327004034922296

In [22]:
np.random.rand(6)

array([0.05711565, 0.12910274, 0.48715005, 0.58341746, 0.40712364,
       0.649394  ])

In [24]:
np.random.randn()

0.21711033900168947

In [25]:
np.random.randn(10)

array([ 0.05825683,  1.81102465,  0.22783502,  1.44840121,  0.32588381,
       -0.86864707,  0.16072938, -0.18905891,  0.76433648, -1.6751703 ])

In [3]:
np.zeros(10)

NameError: name 'np' is not defined